name: Deploy Workflow

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo Site-11
        uses: actions/checkout@v2

      - name: Trigger Workflow in Another Repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            ${{ secrets.REPO_URL }}" \
            -d '{"ref":"main"}'

