name: Add site-11 prs to project
on:
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add pr to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/UofTHacks-Official/projects/21
          github-token: ${{ secrets.GHPROJECT_TOKEN }}